version: "3"
services:
  dummy_nginx:
    container_name: dummy_nginx
    image: mariadb:latest
    build:
      context: .
      dockerfile: ./Dockerfile_nginx
    ports:
      - "31101:80"
  dummy_front:
    container_name: dummy_front
    image: mhart/alpine-node
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "38000:8000"

networks:
  default:
    external:
      name: dummy_network

